services:
    web:
        build: ./php
        ports:
            - "80:80"
            - "3000"
            - "5000"
        restart: always
    node:
        build: ./node
        restart: always
        network_mode: service:web
    flask:
        build: ./flask
        environment:
            FLAG: INTIGRITI{fake_flag}
        restart: always
        network_mode: service:web
